# tickrate = cada x ticks agrega bloques
tickrate: 4

# blockXTick = cantidad de bloques por cada tanda
blockXTick: 150000

# reportOnEveryXBlocks = envia al log cuantos bloques faltan cada X bloques colocados
reportOnEveryXBlocks: 100000