name: LightningSchem
main: fabicorp.LightningSchem
version: 1.0
api-version: 1.16
commands: 
   golpear:
      description: Paste Schematic
      permission: lightningschem.golpear
      permission-message: "You can't do this."
      usage: "/golpear <schem> <x y z> <world>"